// Generated by https://quicktype.io

export interface Register {
    email:           null;
    password:        null;
    confirmPassword: null;
    firstName:       null;
    lastName:        null;
    dateOfBirth:     string;
}
